"""Deterministic prose: nothing here is generated by an LLM.

- literal_meaning: the affix-table glosses of the chosen segmentation,
  joined in word order. Pure table lookup — it cannot originate a fact.
- modern_usage: the word's first sense from the Merriam-Webster Collegiate
  Dictionary API, quoted verbatim. Fetched, not generated. Merriam-Webster's
  sense ordering favors current usage over historical/etymological order
  (unlike the Free Dictionary API this project used at first — its
  Wiktionary-sourced sense 1 for "philosophy" was "the love of wisdom", an
  etymology restatement, not how the word is used today).
"""

from __future__ import annotations

import json
import os
import re
import urllib.error
import urllib.parse
from typing import Sequence

from app.ground import GroundedMorpheme
from app.retrieve import HttpGet, _default_http_get

COMPOSE_VERSION = "compose-v2"  # v2: definition fetched even without glosses

_PIPED_TOKEN = re.compile(r"\{[a-zA-Z_0-9]+\|([^|}]*)[^}]*\}")
_BARE_TOKEN = re.compile(r"\{/?[a-zA-Z_0-9]*\}")


def _surface(m: GroundedMorpheme) -> str:
    if m.type == "prefix":
        return m.surface + "-"
    if m.type == "suffix":
        return "-" + m.surface
    return m.surface


def literal_meaning(morphemes: Sequence[GroundedMorpheme]) -> str | None:
    """Glosses joined in word order, or None when no morpheme has one."""
    if not any(m.meaning for m in morphemes):
        return None
    parts = [
        f'{_surface(m)} "{m.meaning}"' if m.meaning
        else f"{_surface(m)} [unverified]"
        for m in morphemes
    ]
    return " + ".join(parts)


def _mw_key() -> str | None:
    return os.environ.get("WIKIWORD_MW_API_KEY")


def _mw_url(word: str) -> str:
    return (
        "https://www.dictionaryapi.com/api/v3/references/collegiate/json/"
        f"{urllib.parse.quote(word)}?key={_mw_key()}"
    )


def _clean(text: str) -> str:
    """Strip Merriam-Webster's run-in markup tokens (links, cross
    references, italics), keeping the plain display text they wrap. Some
    senses (e.g. "more" -> {sx|greater|...}) are *entirely* a cross
    reference with no other prose, so tokens are flattened to their display
    text rather than dropped — dropping risks an empty definition."""
    text = _PIPED_TOKEN.sub(r"\1", text)
    text = _BARE_TOKEN.sub("", text)
    return re.sub(r"\s+", " ", text).strip()


def _first_text(node) -> str | None:
    """The first ["text", "..."] leaf anywhere in a def/sseq tree — a
    generic walk rather than modeling the full (deeply nested, sense/pseq/
    bs-variant) sseq grammar, since we only ever want sense 1's text."""
    if isinstance(node, list):
        if len(node) == 2 and node[0] == "text" and isinstance(node[1], str):
            return node[1]
        for item in node:
            found = _first_text(item)
            if found is not None:
                return found
    elif isinstance(node, dict):
        for v in node.values():
            found = _first_text(v)
            if found is not None:
                return found
    return None


def fetch_definition(
    word: str, http_get: HttpGet = _default_http_get
) -> tuple[str | None, bool]:
    """(definition, definitive) from the Merriam-Webster Collegiate
    Dictionary API.

    No key configured is a clean, expected "feature disabled" state (like
    llm.is_enabled() being False) — definitive=True, no retry churn.
    definitive=False means a transport failure or an unparseable response
    (e.g. an invalid/revoked key, which the API reports as a 200 plain-text
    error rather than a 4xx) — the caller must not cache the response, so a
    broken key doesn't silently produce "no definition" forever; it stays
    visibly retried instead. A response that's a JSON array of strings
    (MW's spelling-suggestion format) means a definitive miss.
    """
    key = _mw_key()
    if not key:
        return None, True
    try:
        status, body = http_get(_mw_url(word))
    except (OSError, urllib.error.URLError):
        return None, False
    if status != 200:
        return None, False
    try:
        entries = json.loads(body)
    except json.JSONDecodeError:
        return None, False
    if not isinstance(entries, list) or not entries:
        return None, True
    entry = entries[0]
    if not isinstance(entry, dict):
        return None, True  # spelling suggestions: word not in this dictionary
    text = _first_text(entry.get("def"))
    definition = _clean(text) if text else ""
    if not definition:
        return None, True
    pos = entry.get("fl")
    return (f"({pos}) {definition}" if pos else definition), True
